"""
Curated word model for the DfE Year 5/6 statutory spelling list.

Every word carries five layers, because spelling failure happens at different layers:

  1. SOUND      syllables, so we can talk about stress and schwa
  2. STRUCTURE  morphemes (prefix + base + suffix), which is where doubling rules live
  3. ORIGIN     source language and root, which explains the "weird" graphemes
  4. TRAPS      the exact substrings where the spelling is not predictable from sound
  5. FAMILY     words that share a root or a pattern, for pattern-level practice

Field notes:
  syll     hyphenated syllables, UK pronunciation
  lang     Latin | Greek | French | Old English | Old Norse | Dutch | Arabic | Spanish
  root     the source form, kept short
  gloss    what the root means, in plain English
  morph    morpheme split using +, "-" if the word is a single unanalysable base
  traps    substrings that are the actual decision points
  patterns controlled vocabulary, used for scheduling (see PATTERNS below)
  errors   realistic misspellings, used to test the classifier
  why      one line a ten-year-old can hold in their head
  family   3-4 words sharing the root or the pattern
"""

PATTERNS = {
    "assimilated-prefix": "A prefix changes its last letter to match the next sound: ad+com becomes ac+com.",
    "double-consonant": "Two of the same letter, usually where a prefix meets a base.",
    "single-consonant": "Looks like it should double, but does not.",
    "doubling-1-1-1": "One syllable, one short vowel, one final consonant: double before a vowel suffix.",
    "silent-letter": "A letter you cannot hear, usually kept from the older form of the word.",
    "schwa": "An unstressed vowel that sounds like 'uh', so the letter has to be remembered.",
    "ie-ei": "The i/e pair, decided by the root, not by a rhyme.",
    "soft-c-g": "c or g sounding soft because e, i or y follows.",
    "sh-spelling": "The /sh/ sound spelled ci, ti, si or ss.",
    "suffix-ant-ent": "The -ant/-ent choice, set by the Latin verb it came from.",
    "suffix-ance-ence": "The -ance/-ence choice, same rule as -ant/-ent.",
    "suffix-ary-ery": "The -ary/-ery/-ory ending, usually a schwa.",
    "suffix-able-ible": "The -able/-ible choice.",
    "keep-e": "Keep the silent e when adding -ly.",
    "base-change": "The base loses or changes a letter when the suffix goes on.",
    "greek-marker": "Greek loan markers: ph, ch as /k/, y as short i, rh, ps.",
    "french-ending": "A French ending kept whole: -eur, -que, -ant, -et.",
    "ough": "The ough family, one spelling, many sounds.",
    "ou-spelling": "ou doing an unexpected job.",
    "homophone-trap": "A real word sits next door and sounds the same.",
    "unique": "A one-off. Learn it as itself.",
}


def W(word, syll, lang, root, gloss, morph, traps, patterns, errors, why, family):
    return {
        "word": word, "syll": syll, "lang": lang, "root": root, "gloss": gloss,
        "morph": morph, "traps": traps, "patterns": patterns,
        "errors": errors, "why": why, "family": family,
    }


WORDS = [
W("accommodate","ac-com-mo-date","Latin","ad + com + modus","measure, fit","ac+com+mod+ate",
  ["cc","mm"],["assimilated-prefix","double-consonant"],["accomodate","acommodate","acomodate"],
  "Two prefixes stack up, so two doubles: ad becomes ac, then com keeps its m.",
  ["accompany","accord","commodity","modify"]),
W("accompany","ac-com-pa-ny","Latin","ad + com + panis","with bread","ac+com+pan+y",
  ["cc"],["assimilated-prefix","double-consonant","single-consonant"],["acompany","accompanie"],
  "A companion shares bread with you. Double c from ad, single p from panis.",
  ["accommodate","company","companion","pantry"]),
W("according","ac-cord-ing","Latin","ad + cor, cordis","heart","ac+cord+ing",
  ["cc"],["assimilated-prefix","double-consonant"],["acording","accordeing"],
  "To accord is to bring hearts together, so cord, with cc from ad.",
  ["accord","cordial","record","courage"]),
W("achieve","a-chieve","French","a chief","to a head","a+chieve",
  ["ie"],["ie-ei"],["acheive","achive","acheve"],
  "You bring a thing to a head, to a chief. The i comes before the e.",
  ["chief","mischief","believe","relieve"]),
W("aggressive","ag-gres-sive","Latin","ad + gradi, gressus","to step","ag+gress+ive",
  ["gg","ss"],["assimilated-prefix","double-consonant"],["agressive","aggresive"],
  "Ad becomes ag before gress, to step at someone. Then gress keeps its ss.",
  ["progress","congress","digress","gradual"]),
W("amateur","am-a-teur","French","amator, amare","to love","amat+eur",
  ["eur"],["french-ending","schwa"],["amature","amatuer","ammateur"],
  "An amateur does it for love. The -eur ending is French and stays whole.",
  ["amorous","entrepreneur","chauffeur","grandeur"]),
W("ancient","an-cient","French","ante","before","anci+ent",
  ["cie"],["sh-spelling","suffix-ant-ent"],["anceint","anchient","ancint"],
  "The /sh/ here is spelled ci, the same trick as in sufficient.",
  ["sufficient","efficient","conscience","antique"]),
W("apparent","ap-par-ent","Latin","ad + parere","to appear","ap+par+ent",
  ["pp","ent"],["assimilated-prefix","double-consonant","suffix-ant-ent"],["aparent","apparant"],
  "It appears, so ad plus parere gives pp. Latin -ent verbs take -ent.",
  ["appear","apparition","transparent","parent"]),
W("appreciate","ap-pre-ci-ate","Latin","ad + pretium","price","ap+preci+ate",
  ["pp","ci"],["assimilated-prefix","double-consonant","sh-spelling"],["apreciate","appriciate"],
  "To appreciate is to set a price on it. Price gives the ci.",
  ["price","precious","appraise","depreciate"]),
W("attached","at-tached","French","atachier","to fasten","at+tach+ed",
  ["tt"],["double-consonant"],["atached","attatched"],
  "Ad becomes at before tach. One t would make a different word.",
  ["attach","attack","detach","attain"]),
W("available","a-vail-a-ble","Latin","ad + valere","to be strong, worth","a+vail+able",
  ["ai","able"],["suffix-able-ible","schwa"],["avaliable","availible","availabe"],
  "Avail means to be of worth. Add -able because avail is a whole word.",
  ["value","valid","prevail","valuable"]),
W("average","av-er-age","Arabic","awar","damage to cargo","aver+age",
  ["er","age"],["schwa"],["avrage","averige","avarage"],
  "A sea-trade word for sharing damage costs. The middle e is a lazy 'uh'.",
  ["courage","damage","village","voyage"]),
W("awkward","awk-ward","Old Norse","afugr + -ward","turned the wrong way","awk+ward",
  ["wkw"],["unique"],["akward","awkard","awkwerd"],
  "Norse afugr means back to front, plus -ward, direction. Three letters, w-k-w.",
  ["backward","forward","toward","wayward"]),
W("bargain","bar-gain","French","bargaignier","to haggle","bar+gain",
  ["ain"],["schwa"],["bargin","bargian","barganin"],
  "The ending is -ain, the same lazy ending as captain and mountain.",
  ["captain","mountain","villain","certain"]),
W("bruise","bruise","Old English","brysan","to crush","-",
  ["ui","se"],["ou-spelling"],["bruse","bruze","brusie"],
  "Old English crushing plus a French spelling, so ui, and s not z.",
  ["cruise","juice","fruit","suit"]),
W("category","cat-e-go-ry","Greek","kategoria","a statement, an accusation","categor+y",
  ["e","ory"],["schwa","suffix-ary-ery"],["catagory","catergory","catogory"],
  "Greek word for a public statement. The middle e and the -ory are both schwa.",
  ["categorise","allegory","memory","territory"]),
W("cemetery","cem-e-ter-y","Greek","koimeterion","sleeping place","cemeter+y",
  ["e","ery"],["schwa","suffix-ary-ery"],["cemetary","cemetry","cematery"],
  "Greek for a sleeping place. Three e's in a row of syllables, no a anywhere.",
  ["monastery","mystery","stationery","bakery"]),
W("committee","com-mit-tee","Latin","com + mittere","to send with","com+mitt+ee",
  ["mm","tt","ee"],["double-consonant","doubling-1-1-1"],["commitee","comittee","committe"],
  "Commit doubles its t before -ee. Two m, two t, two e, in that order.",
  ["commit","submit","transmit","mission"]),
W("communicate","com-mu-ni-cate","Latin","communis","common, shared","commun+ic+ate",
  ["mm"],["double-consonant","single-consonant"],["comunicate","communciate"],
  "From common. Double m from com plus mun, then a single n.",
  ["community","common","communion","municipal"]),
W("community","com-mu-ni-ty","Latin","communis","common, shared","commun+ity",
  ["mm"],["double-consonant"],["comunity","comunnity"],
  "Same root as common and communicate, so the same double m.",
  ["communicate","common","commune","municipal"]),
W("competition","com-pe-ti-tion","Latin","com + petere","to seek together","com+pet+ition",
  ["e","tition"],["schwa","sh-spelling"],["compitition","competion","competiton"],
  "Compete keeps its e even though you cannot hear it. Then -ition.",
  ["compete","petition","appetite","repetition"]),
W("conscience","con-science","Latin","com + scire","to know with","con+sci+ence",
  ["sci","ence"],["sh-spelling","suffix-ance-ence"],["consience","concience","conshence"],
  "Hidden inside is science, to know. Knowing with yourself.",
  ["science","conscious","omniscient","scientist"]),
W("conscious","con-scious","Latin","com + scire","to know with","con+sci+ous",
  ["sci","ous"],["sh-spelling"],["concious","conscius","conshus"],
  "Same hidden science as conscience, then -ous for the adjective.",
  ["conscience","science","subconscious","scientific"]),
W("controversy","con-tro-ver-sy","Latin","contra + vertere","to turn against","contro+vers+y",
  ["o","vers"],["schwa"],["contraversy","controvesy","contraversey"],
  "Contra means against, vers means turn. Turned against each other.",
  ["convert","reverse","adverse","version"]),
W("convenience","con-ven-ience","Latin","com + venire","to come together","con+veni+ence",
  ["ience"],["suffix-ance-ence"],["convienence","conveniance","convience"],
  "Things that come together suit you. Venire gives -ien, then -ence.",
  ["convene","intervene","avenue","event"]),
W("correspond","cor-re-spond","Latin","com + respondere","to answer together","cor+respond",
  ["rr"],["assimilated-prefix","double-consonant"],["corespond","correspound"],
  "Com becomes cor before respond, so two r's meet in the middle.",
  ["respond","response","sponsor","correlate"]),
W("criticise","crit-i-cise","Greek","kritikos","able to judge","critic+ise",
  ["c","ise"],["soft-c-g"],["critisise","critiscise","criticice"],
  "From critic. The c stays c, and British English takes -ise.",
  ["critic","crisis","criterion","critical"]),
W("curiosity","cu-ri-os-i-ty","Latin","cura","care","curi+os+ity",
  ["ios"],["base-change"],["curiousity","curiosty","curiocity"],
  "Curious loses its u when it becomes curiosity. Care, not carelessness.",
  ["curious","cure","accurate","secure"]),
W("definite","def-i-nite","Latin","de + finis","boundary, end","de+fin+ite",
  ["i","ite"],["schwa"],["definate","definante","defenite"],
  "Finis means end, so there is a finite hiding inside. Never an a.",
  ["finish","final","infinite","define"]),
W("desperate","des-per-ate","Latin","de + sperare","to hope","de+sper+ate",
  ["per"],["schwa"],["desparate","desperete"],
  "Despair is inside it, hope gone. Sperare gives -per-, never -par-.",
  ["despair","prosper","desperation","aspire"]),
W("determined","de-ter-mined","Latin","de + terminus","limit, boundary","de+termin+ed",
  ["r","min"],["single-consonant"],["determind","detirmined","determinded"],
  "You set a limit, a terminus. One r, and -mined like the word mine.",
  ["terminate","term","exterminate","terminal"]),
W("develop","de-vel-op","French","desveloper","to unwrap","de+velop",
  ["p"],["single-consonant"],["developp","develope","devlop"],
  "Envelope wraps up, develop unwraps. No e on the end, no double p.",
  ["envelope","envelop","development","developer"]),
W("dictionary","dic-tion-ar-y","Latin","dicere","to say","dict+ion+ary",
  ["tion","ary"],["sh-spelling","suffix-ary-ery"],["dictionery","dictonary","dictionry"],
  "A book of sayings. Dict means say, so dictate and predict are cousins.",
  ["dictate","predict","verdict","contradict"]),
W("disastrous","di-sas-trous","Latin","dis + astrum","bad star","dis+astr+ous",
  ["astr"],["base-change"],["disasterous","disastorous"],
  "Disaster loses its e before -ous. An ill-starred event.",
  ["disaster","astronomy","asterisk","astronaut"]),
W("embarrass","em-bar-rass","French","embarrasser","to block, to bar","em+barr+ass",
  ["rr","ss"],["double-consonant"],["embarass","embarras","embarrase"],
  "Really Red and Super Shy. Two r, two s, unlike harass.",
  ["harass","bar","barrier","embargo"]),
W("environment","en-vi-ron-ment","French","environ","around","environ+ment",
  ["nm"],["silent-letter"],["enviroment","envirnoment","enviornment"],
  "Environ means around. Keep its n, then add -ment. You cannot hear it.",
  ["environs","government","environmental","iron"]),
W("equipment","e-quip-ment","French","equiper","to fit out a ship","equip+ment",
  ["p"],["single-consonant","doubling-1-1-1"],["equiptment","equipement","equippment"],
  "-ment starts with a consonant, so equip does not double. Compare equipped.",
  ["equip","equipped","shipment","commitment"]),
W("equipped","e-quipped","French","equiper","to fit out a ship","equip+ped",
  ["pp"],["doubling-1-1-1","double-consonant"],["equiped","equippd"],
  "-ed starts with a vowel, so the p doubles. Compare equipment.",
  ["equip","equipment","shipped","stopped"]),
W("especially","es-pe-cial-ly","Latin","specialis","of a kind","e+speci+al+ly",
  ["ci","ll"],["sh-spelling","double-consonant"],["expecially","especialy","especally"],
  "Special plus -ly, so two l's. The /sh/ is ci, from species.",
  ["special","species","specific","specially"]),
W("exaggerate","ex-ag-ger-ate","Latin","ex + agger","a heap","ex+agger+ate",
  ["gg"],["double-consonant"],["exagerate","exagurate","exadgerate"],
  "Agger is a heap. To exaggerate is to heap it up, so gg.",
  ["aggregate","exaggeration","gesture","exert"]),
W("excellent","ex-cel-lent","Latin","ex + cellere","to rise above","ex+cell+ent",
  ["ll","ent"],["double-consonant","suffix-ant-ent"],["excelent","excellant","exelent"],
  "Excel doubles its l before -ent. Rising above the rest.",
  ["excel","excellence","cellar","exceed"]),
W("existence","ex-ist-ence","Latin","ex + sistere","to stand out","ex+ist+ence",
  ["ence"],["suffix-ance-ence"],["existance","existince","exsistence"],
  "To exist is to stand out. Latin -ere verbs take -ence, not -ance.",
  ["exist","insist","resist","persistence"]),
W("explanation","ex-pla-na-tion","Latin","ex + planus","flat, clear","ex+plan+ation",
  ["plan"],["base-change"],["explaination","explanaition","explantion"],
  "Explain loses its i here. Making something flat and plain.",
  ["explain","plain","plane","explanatory"]),
W("familiar","fa-mil-iar","Latin","familia","household","famili+ar",
  ["iar"],["schwa"],["familar","familliar","femiliar"],
  "Family plus -ar. Known to the household.",
  ["family","familiarity","familial","peculiar"]),
W("foreign","for-eign","French","foris","outside, out of doors","foreign",
  ["eig","g"],["silent-letter","ie-ei"],["foriegn","forign","foreighn"],
  "From outside. The g was added later by copying reign, so it is silent.",
  ["sovereign","reign","forest","forfeit"]),
W("forty","for-ty","Old English","feowertig","four tens","for+ty",
  ["or"],["base-change"],["fourty","fourthy"],
  "Four keeps its u, forty drops it. English changed its mind in the 1500s.",
  ["four","fourteen","fourth","fortieth"]),
W("frequently","fre-quent-ly","Latin","frequens","crowded, repeated","frequent+ly",
  ["qu","ent"],["suffix-ant-ent"],["frequantly","freqently","frequenly"],
  "Frequens means crowded. Latin -ens becomes English -ent.",
  ["frequent","frequency","sequence","consequence"]),
W("government","gov-ern-ment","French","gubernare","to steer a ship","govern+ment",
  ["nm"],["silent-letter"],["goverment","govenment","govermant"],
  "Govern plus -ment. Keep the n, even though nobody says it.",
  ["govern","governor","environment","gubernatorial"]),
W("guarantee","guar-an-tee","French","garant","a warrant","guar+antee",
  ["gua","ee"],["french-ending"],["garantee","guarentee","guarante"],
  "Guard and guarantee share the gua. The ending is -tee, like referee.",
  ["guard","guardian","warranty","referee"]),
W("harass","ha-rass","French","harasser","to set a dog on","har+ass",
  ["r","ss"],["single-consonant"],["harrass","harras","harrassed"],
  "One r, two s. The opposite pattern to embarrass, which has both doubled.",
  ["embarrass","harassment","harried","assail"]),
W("hindrance","hin-drance","Old English","hindrian","to hold back","hindr+ance",
  ["dr","ance"],["base-change","suffix-ance-ence"],["hinderance","hindrence"],
  "Hinder loses its e before -ance. Say it: hin-drance, two syllables.",
  ["hinder","remembrance","entrance","encumbrance"]),
W("identity","i-den-ti-ty","Latin","idem","the same","ident+ity",
  ["ti"],["schwa"],["identiy","indentity","identety"],
  "Idem means the same. Your identity is what stays the same. No n after i.",
  ["identical","identify","idem","identification"]),
W("immediate","im-me-di-ate","Latin","in + medius","middle","im+medi+ate",
  ["mm","iate"],["assimilated-prefix","double-consonant"],["imediate","immediat","immeadiate"],
  "In becomes im before m: nothing in the middle, so it happens now.",
  ["immediately","mediate","medium","middle"]),
W("immediately","im-me-di-ate-ly","Latin","in + medius","middle","im+medi+ate+ly",
  ["mm","ely"],["keep-e","double-consonant"],["immediatly","imediately","immeadiately"],
  "Keep the e of immediate before -ly. Same rule as definitely and sincerely.",
  ["immediate","definitely","sincerely","completely"]),
W("individual","in-di-vid-u-al","Latin","in + dividere","not dividable","in+divid+ual",
  ["ual"],["schwa"],["indavidual","indevidual","invidual"],
  "Not divisible: divide is inside it. Then the -ual ending, like usual.",
  ["divide","division","individually","usual"]),
W("interfere","in-ter-fere","French","inter + ferire","to strike between","inter+fere",
  ["fere"],["schwa"],["interfear","intefere","interfeer"],
  "To strike between two things. The ending is -fere, not -fear.",
  ["interference","interrupt","interval","transfer"]),
W("interrupt","in-ter-rupt","Latin","inter + rumpere","to break between","inter+rupt",
  ["rr"],["double-consonant"],["interupt","interrup","intterupt"],
  "Inter ends in r, rupt starts with r. Break between, so two r's.",
  ["rupture","erupt","corrupt","abrupt"]),
W("language","lan-guage","French","lingua","tongue","langu+age",
  ["gua","age"],["silent-letter","schwa"],["langauge","languge","langige"],
  "Lingua is a tongue. The u after g is silent, the -age is a lazy 'ij'.",
  ["linguist","bilingual","tongue","guard"]),
W("leisure","lei-sure","French","licere","to be allowed","leis+ure",
  ["ei","sure"],["ie-ei"],["liesure","lesure","leasure"],
  "Time you are allowed. This one is e before i, unlike achieve.",
  ["seizure","pleasure","measure","licence"]),
W("lightning","light-ning","Old English","lihtan","to make light","lightn+ing",
  ["tn"],["base-change","homophone-trap"],["lightening","lighting","lightnening"],
  "Lightning drops the e of lighten. Lightening means getting brighter.",
  ["light","lighten","frighten","brighten"]),
W("marvellous","mar-vel-lous","French","mirabilia","wonderful things","marvel+lous",
  ["ll","ous"],["double-consonant"],["marvelous","marvellus","marvelious"],
  "British English doubles the l of marvel before -ous. American English does not.",
  ["marvel","miracle","admire","mirror"]),
W("mischievous","mis-chie-vous","French","meschief","bad outcome","mis+chiev+ous",
  ["ie","vous"],["ie-ei","base-change"],["mischievious","mischevious","mischeivous"],
  "Three syllables, not four. Mischief plus -ous, and no extra i.",
  ["mischief","chief","achieve","grievous"]),
W("muscle","mus-cle","Latin","musculus","little mouse","muscl+e",
  ["sc","cle"],["silent-letter","homophone-trap"],["mussle","muscel","musle"],
  "A flexing muscle looked like a mouse under the skin. Muscular shows the c.",
  ["muscular","mussel","mouse","corpuscle"]),
W("necessary","nec-es-sar-y","Latin","necesse","unavoidable","necess+ary",
  ["c","ss","ary"],["single-consonant","double-consonant","suffix-ary-ery"],
  ["neccessary","necesary","nessesary"],
  "One collar, two sleeves: one c, two s. Then -ary.",
  ["necessity","necessarily","accessory","cease"]),
W("neighbour","neigh-bour","Old English","neah + gebur","near dweller","neigh+bour",
  ["eigh","our"],["ie-ei","ou-spelling"],["nieghbour","neighbor","naighbour"],
  "The person who dwells near. Same eigh as eight and weigh.",
  ["eight","weigh","weight","harbour"]),
W("nuisance","nui-sance","French","nocere","to harm","nuis+ance",
  ["ui","ance"],["suffix-ance-ence","ou-spelling"],["nuisence","nusance","nuisanse"],
  "Something that harms you a little. French ui, then -ance.",
  ["innocent","noxious","annoyance","juice"]),
W("occupy","oc-cu-py","Latin","ob + capere","to seize","oc+cup+y",
  ["cc","p"],["assimilated-prefix","double-consonant","single-consonant"],["ocupy","occuppy"],
  "Ob becomes oc before c. To seize a space. One p.",
  ["occur","occasion","capture","occupation"]),
W("occur","oc-cur","Latin","ob + currere","to run towards","oc+cur",
  ["cc","r"],["assimilated-prefix","doubling-1-1-1"],["ocur","occurr","occure"],
  "Ob becomes oc, then curr means run. One r here, two in occurred.",
  ["occurred","current","recur","excursion"]),
W("opportunity","op-por-tu-ni-ty","Latin","ob + portus","towards the harbour","op+portun+ity",
  ["pp","r"],["assimilated-prefix","double-consonant"],["oportunity","opperchunity","opportuinty"],
  "A wind blowing towards the harbour. Ob becomes op before port.",
  ["port","import","portable","transport"]),
W("parliament","par-lia-ment","French","parler","to speak","parli+ament",
  ["lia"],["silent-letter"],["parlament","parliment","parlement"],
  "A place for speaking, from French parler. The hidden i is the giveaway.",
  ["parley","parlour","parole","parliamentary"]),
W("persuade","per-suade","Latin","per + suadere","to urge thoroughly","per+suade",
  ["sua"],["schwa"],["perswade","pursuade","persaude"],
  "Per means thoroughly. Never spell it pur-, and never swade.",
  ["persuasion","dissuade","suave","perfect"]),
W("physical","phys-i-cal","Greek","physis","nature","physic+al",
  ["ph","y"],["greek-marker"],["fisical","physicle","phisical"],
  "Greek gives ph for /f/ and y for short i. Nature, as in the body.",
  ["physics","physician","physiology","physique"]),
W("prejudice","prej-u-dice","Latin","prae + judicium","judgement before","pre+judic+e",
  ["j","dice"],["soft-c-g"],["predjudice","prejadice","prejudise"],
  "Judging before you know. Judge is inside it, with no d before the j.",
  ["judge","judicial","prejudge","judgement"]),
W("privilege","priv-i-lege","Latin","privus + lex","private law","privi+lege",
  ["lege"],["soft-c-g"],["priviledge","privelege","privilage"],
  "A private law, just for you. Lex means law, so -lege, no d.",
  ["legal","legislate","private","legislation"]),
W("profession","pro-fes-sion","Latin","pro + fateri","to declare publicly","pro+fess+ion",
  ["ss","ion"],["double-consonant","sh-spelling"],["proffesion","professon","profesion"],
  "You profess, you declare. One f, two s, like confess.",
  ["professor","confess","profess","possession"]),
W("programme","pro-gramme","Greek","pro + gramma","written before","pro+gramme",
  ["mm","amme"],["greek-marker","double-consonant"],["program","programe","progrmme"],
  "Gramma means writing, as in grammar and diagram. British English keeps -mme.",
  ["grammar","diagram","telegram","anagram"]),
W("pronunciation","pro-nun-ci-a-tion","Latin","pro + nuntiare","to announce","pro+nunci+ation",
  ["nun","ci"],["base-change","sh-spelling"],["pronounciation","pronunciaton","prounciation"],
  "Pronounce has ou, pronunciation does not. The noun lost it in Latin.",
  ["pronounce","announce","denounce","enunciate"]),
W("queue","queue","French","cauda","tail","queue",
  ["ueue"],["french-ending","unique"],["que","queu","quewe"],
  "A tail of people. One letter doing the work, with four just queueing behind.",
  ["cue","barbecue","tail","query"]),
W("recognise","rec-og-nise","Latin","re + cognoscere","to know again","re+cogn+ise",
  ["g","ise"],["silent-letter"],["reconise","recognize","reconize"],
  "To know again. Cogn means know, so the g must be there even if you skip it.",
  ["cognition","incognito","recognition","diagnose"]),
W("recommend","rec-om-mend","Latin","re + com + mandare","to entrust again","re+com+mend",
  ["c","mm"],["single-consonant","double-consonant"],["reccomend","recomend","reccommend"],
  "Re plus commend. One c, two m, because the double belongs to commend.",
  ["commend","command","mandate","demand"]),
W("relevant","rel-e-vant","Latin","re + levare","to lift up","relev+ant",
  ["e","ant"],["schwa","suffix-ant-ent"],["relevent","relavent","relevunt"],
  "It lifts the point up. Levare also gives lever and elevate.",
  ["relieve","elevate","lever","relevance"]),
W("restaurant","res-tau-rant","French","restaurer","to restore","restaur+ant",
  ["au","ant"],["french-ending"],["restrant","restaraunt","resturant"],
  "A place that restores you. Restore plus a French -ant ending.",
  ["restore","restaurateur","restoration","assistant"]),
W("rhyme","rhyme","Greek","rhythmos","measured flow","rhyme",
  ["rh","y"],["greek-marker"],["rime","ryme","rhime"],
  "Rhyme borrowed its rh and y from rhythm, its Greek cousin.",
  ["rhythm","rhetoric","rhinoceros","rhubarb"]),
W("rhythm","rhy-thm","Greek","rhythmos","flow","rhythm",
  ["rh","y","thm"],["greek-marker"],["rythm","rhythem","rythem"],
  "No a, e, i, o or u anywhere. Both y's are doing vowel work.",
  ["rhyme","myth","gym","hymn"]),
W("sacrifice","sac-ri-fice","Latin","sacer + facere","to make holy","sacri+fice",
  ["i","fice"],["soft-c-g"],["sacrafice","sacrifise","sacrefice"],
  "To make holy. Facere, to make, becomes -fice, as in office.",
  ["sacred","sacrament","office","factory"]),
W("secretary","sec-re-tar-y","Latin","secretum","a secret","secret+ary",
  ["e","ary"],["schwa","suffix-ary-ery"],["secratary","secertary","secretery"],
  "The keeper of secrets. Secret is whole inside it, then -ary.",
  ["secret","secrecy","secretive","library"]),
W("shoulder","shoul-der","Old English","sculdor","shoulder","shoulder",
  ["ou"],["ou-spelling"],["sholder","shoulda","sholuder"],
  "The ou here says 'oh', as it also does in boulder and smoulder.",
  ["boulder","smoulder","mould","soul"]),
W("signature","sig-na-ture","Latin","signum","a sign","sign+ature",
  ["g","ature"],["silent-letter"],["signiture","signeture","singature"],
  "Sign hides its g, signature says it out loud. Same word underneath.",
  ["sign","design","signal","resign"]),
W("sincere","sin-cere","Latin","sincerus","pure, clean","sin+cere",
  ["cere"],["soft-c-g"],["sincear","sinsere","sincer"],
  "Latin for pure. The ending is -cere, soft c before e.",
  ["sincerely","sincerity","insincere","cereal"]),
W("sincerely","sin-cere-ly","Latin","sincerus","pure, clean","sin+cere+ly",
  ["ely"],["keep-e"],["sincerly","sincerley","sincerelly"],
  "Sincere keeps its e before -ly. Same rule as immediately.",
  ["sincere","immediately","definitely","completely"]),
W("soldier","sol-dier","French","solidus","a gold coin","sold+ier",
  ["dier"],["schwa"],["soldior","solider","soljer"],
  "Paid in solidus coins, so soldier holds the word sold.",
  ["solid","soldiery","salary","sold"]),
W("stomach","stom-ach","Greek","stomachos","gullet, mouth","stomach",
  ["ch"],["greek-marker"],["stomache","stumach","stomac"],
  "Greek ch says /k/, as in chorus, character and echo.",
  ["chorus","character","echo","ache"]),
W("sufficient","suf-fi-cient","Latin","sub + facere","to make up to","suf+fici+ent",
  ["ff","cie"],["assimilated-prefix","sh-spelling","suffix-ant-ent"],["suficient","sufficent"],
  "Sub becomes suf before f. The /sh/ is ci, as in ancient.",
  ["ancient","efficient","suffice","suffix"]),
W("suggest","sug-gest","Latin","sub + gerere","to carry under","sug+gest",
  ["gg"],["assimilated-prefix","double-consonant"],["sugest","sugjest","suggeste"],
  "Sub becomes sug before g. You carry an idea up from underneath.",
  ["digest","gesture","register","suggestion"]),
W("symbol","sym-bol","Greek","symbolon","a token thrown together","sym+bol",
  ["y","ol"],["greek-marker","homophone-trap"],["simbol","symbal","cymbol"],
  "Greek y for short i. A cymbal is the instrument, a symbol is the sign.",
  ["symmetry","sympathy","synonym","cymbal"]),
W("system","sys-tem","Greek","systema","set up together","sys+tem",
  ["y"],["greek-marker"],["sistem","systum","sistum"],
  "Greek y again, saying short i. Things standing together.",
  ["symbol","syllable","synthesis","systematic"]),
W("temperature","tem-per-a-ture","Latin","temperare","to mix, to moderate","temper+ature",
  ["per","ature"],["schwa"],["temprature","temperture","tempreture"],
  "Temper is inside it: a mixing. Say all four syllables to spell it.",
  ["temper","temperate","temperament","signature"]),
W("thorough","thor-ough","Old English","thuruh","through","thorough",
  ["ough"],["ough","homophone-trap"],["thourough","thorogh","thourgh"],
  "Thorough is through with an extra syllable. Same family, same ough.",
  ["through","borough","although","dough"]),
W("twelfth","twelfth","Old English","twelfta","twelfth","twelf+th",
  ["fth"],["unique"],["twelth","twelvth","twelfeth"],
  "Twelve turns its v into f, then adds th. Three consonants, all needed.",
  ["twelve","fifth","twentieth","month"]),
W("variety","va-ri-e-ty","Latin","varius","changing, spotted","vari+ety",
  ["iety"],["schwa"],["variaty","vareity","varity"],
  "Vary plus -iety. Four syllables, so say it slowly to hear the e.",
  ["various","vary","variable","society"]),
W("vegetable","veg-e-ta-ble","Latin","vegetare","to enliven","veget+able",
  ["e","able"],["schwa","suffix-able-ible"],["vegtable","vegatable","vegitable"],
  "Say veg-e-table, four syllables. The hidden e is the one people drop.",
  ["vegetation","vegetate","comfortable","suffix"]),
W("vehicle","ve-hi-cle","Latin","vehiculum","carrier","vehic+le",
  ["h","cle"],["silent-letter"],["veicle","vehicel","vehical"],
  "Vehere means to carry. The h is silent here but loud in vehicular.",
  ["vehicular","convey","conveyance","obstacle"]),
W("yacht","yacht","Dutch","jacht","a hunting ship","yacht",
  ["ach"],["unique","silent-letter"],["yatch","yot","yaught"],
  "Dutch jachtschip, a hunting ship. English kept the Dutch letters, not the sounds.",
  ["Dutch loans: sketch","landscape","skipper","cruise"]),
]

assert len({w["word"] for w in WORDS}) == len(WORDS), "duplicate words"
