"""
Copy the built front end into the production site's Games folder.

    python3 tools/deploy_to_site.py [path-to-productionsite]

Default target is a `productionsite` checkout beside this repo. Python rather
than a shell script so it runs on Peter's Windows machine as well as CI.

DayReview is the source of truth. The copy under `Games/Spelling/` is a
DEPLOYMENT ARTEFACT: edit it there and the next run of this script silently
throws the change away. See docs/13-hosting.md.

Deliberately excluded:
  data/firebase.json          never in git, and must never be served. Its
                              presence is what switches sync ON, and docs/06
                              standard 7 is high privacy by default.
  data/firebase.example.json  developer documentation, not site content.
"""
import pathlib
import shutil
import subprocess
import sys
from datetime import date

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "web"
EXCLUDE = {"firebase.json", "firebase.example.json"}

README = """# Spelling: deployed copy, do not edit here

Generated by `tools/deploy_to_site.py` in **TSTPeter/DayReview**, which is the
source of truth. Anything changed in this folder is overwritten by the next
sync. Fix it in DayReview `web/` and re-run the script.

Source commit: {commit}
Synced: {when}

Served at `/Spelling`, routed in `staticwebapp.config.json`.

Fully client-side: no API, no account, no analytics, and no data leaves the
device. The learner record lives in the browser's IndexedDB. Sync is off and
there is deliberately no `data/firebase.json`.
"""


def short_head(repo):
    try:
        out = subprocess.run(["git", "-C", str(repo), "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True, check=True)
        return out.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def main(argv):
    site = pathlib.Path(argv[1]).resolve() if len(argv) > 1 else ROOT.parent / "productionsite"
    dest = site / "Games" / "Spelling"

    if not (site / ".git").exists():
        sys.exit(f"not a git checkout: {site}")
    if not (SRC / "index.html").exists():
        sys.exit(f"no front end at: {SRC}")
    # Refuse rather than ship a config that switches sync on for every visitor.
    if (SRC / "data" / "firebase.json").exists():
        sys.exit("REFUSING: web/data/firebase.json exists. Sync must stay off on "
                 "the public site (docs/06 standard 7). Move it aside and re-run.")

    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(SRC, dest,
                    ignore=lambda _d, names: [n for n in names if n in EXCLUDE])

    (dest / "README.md").write_text(
        README.format(commit=short_head(ROOT), when=date.today().isoformat()))

    # ProductionSite's CLAUDE.md bans em-dashes and en-dashes in every file in
    # that repo, UI copy and code comments alike. This is a build step writing
    # into it, so the rule is enforced here rather than remembered.
    TEXT = {".html", ".js", ".css", ".json", ".md"}
    offenders = sorted(
        str(f.relative_to(dest)) for f in dest.rglob("*")
        if f.is_file() and f.suffix in TEXT
        and any(c in f.read_text(encoding="utf-8") for c in "\u2014\u2013"))
    if offenders:
        sys.exit("REFUSING: em/en dashes are banned on the target site "
                 f"(its CLAUDE.md). Fix in web/ and re-run: {offenders}")

    n = sum(1 for p in dest.rglob("*") if p.is_file())
    print(f"synced {n} files -> {dest}")
    leaked = [p for p in dest.rglob("firebase*.json")]
    if leaked:                       # belt and braces; the ignore above handles it
        sys.exit(f"REFUSING: firebase config reached the site: {leaked}")


if __name__ == "__main__":
    main(sys.argv)
