"""
Copy the built front end into the production site's Games folder.

    python3 tools/deploy_to_site.py [path-to-productionsite]

Default target is a `productionsite` checkout beside this repo. Python rather
than a shell script so it runs on Peter's Windows machine as well as CI.

DayReview is the source of truth. The copy under `Games/Spelling/` is a
DEPLOYMENT ARTEFACT: edit it there and the next run of this script silently
throws the change away. See docs/13-hosting.md.

Deliberately excluded:
  data/firebase.json          never in git, and must never be served. The app
                              takes its config pasted on the one tablet that
                              syncs, but a served config would switch sync on
                              for every visitor, so one is still refused here:
                              docs/06 standard 7 is high privacy by default.
"""
import hashlib
import json
import pathlib
import re
import shutil
import subprocess
import sys
from datetime import date

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "web"
EXCLUDE = {"firebase.json"}

README = """# Spelling: deployed copy, do not edit here

Generated by `tools/deploy_to_site.py` in **TSTPeter/DayReview**, which is the
source of truth. Anything changed in this folder is overwritten by the next
sync. Fix it in DayReview `web/` and re-run the script.

Source commit: {commit}
Synced: {when}

Served at `/Spelling`, routed in `staticwebapp.config.json`.

Fully client-side: no API, no account, no analytics, and no data leaves the
device unless a family pastes its own Firebase config into the grown-up view on
its own tablet, and then only counts. The learner record lives in the browser's
IndexedDB. There is deliberately no `data/firebase.json`.
"""


def short_head(repo):
    try:
        out = subprocess.run(["git", "-C", str(repo), "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True, check=True)
        return out.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


# Written after the stamp, so they cannot be part of what it hashes.
UNHASHED = ("sw.js", "README.md", "version.json")

# ProductionSite's CLAUDE.md bans em and en dashes in every file, UI copy included. A
# dash reaches a reader three ways: the character itself, an HTML entity (the one named
# mdash), or a JavaScript escape (backslash, u, 2014). The rule is about what a person
# reads, so all three are refused. The first check looked only for the character, and on
# 6 October 2026 an entity in the week screen and an escape in the rule card had both
# got through to the live site.
TEXT = {".html", ".js", ".css", ".json", ".md", ".svg"}
DASH = re.compile(
    r"[\u2013\u2014]"                               # the characters
    r"|&(?:mdash|ndash);|&#(?:0*8211|0*8212|x0*201[34]);"   # HTML entities
    r"|\\u201[34]|\\u\{201[34]\}",                    # JavaScript escapes
    re.IGNORECASE)


def dash_offenders(root):
    """Every text file under root that has an em or en dash in any of those forms."""
    return sorted(
        str(f.relative_to(root)) for f in pathlib.Path(root).rglob("*")
        if f.is_file() and f.suffix in TEXT and DASH.search(f.read_text(encoding="utf-8")))


def stamp_cache_version(dest):
    digest = hashlib.sha256()
    for f in sorted(dest.rglob("*")):
        if f.is_file() and f.name not in UNHASHED:
            digest.update(str(f.relative_to(dest)).encode("utf-8"))
            digest.update(f.read_bytes())
    sw = dest / "sw.js"
    text = sw.read_text(encoding="utf-8")
    pattern = re.compile(r"const CACHE = `\$\{PREFIX\}[^`]*`;")
    if len(pattern.findall(text)) != 1:
        sys.exit("REFUSING: could not find the CACHE line in sw.js to stamp. "
                 "If it was renamed, update stamp_cache_version().")
    stamp = digest.hexdigest()[:12]
    stamped = pattern.sub("const CACHE = `${PREFIX}" + stamp + "`;", text)
    sw.write_text(stamped, encoding="utf-8")
    return stamp


def main(argv):
    site = pathlib.Path(argv[1]).resolve() if len(argv) > 1 else ROOT.parent / "productionsite"
    dest = site / "Games" / "Spelling"

    if not (site / ".git").exists():
        sys.exit(f"not a git checkout: {site}")
    if not (SRC / "index.html").exists():
        sys.exit(f"no front end at: {SRC}")
    # Refuse rather than ship a config that switches sync on for every visitor.
    if (SRC / "data" / "firebase.json").exists():
        sys.exit("REFUSING: web/data/firebase.json exists. Sync must stay off on "
                 "the public site (docs/06 standard 7). Move it aside and re-run.")

    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(SRC, dest,
                    ignore=lambda _d, names: [n for n in names if n in EXCLUDE])

    # The service worker serves the shell cache-first and only drops an old cache when
    # its version string changes. A sync that changed words, sentences or clips but
    # not that string would never reach an installed tablet: the new files would sit
    # on the server while the iPad kept playing the old ones. So the deployed copy is
    # versioned by its content, and every sync that changes anything is picked up.
    stamp = stamp_cache_version(dest)

    # Which version a device is running, for the grown-up view. It is in the service
    # worker's shell, so a device always reports the version it is actually showing.
    (dest / "data" / "version.json").write_text(json.dumps(
        {"stamp": stamp, "commit": short_head(ROOT), "synced": date.today().isoformat()},
        indent=2) + "\n", encoding="utf-8")

    (dest / "README.md").write_text(
        README.format(commit=short_head(ROOT), when=date.today().isoformat()))

    # ProductionSite's CLAUDE.md bans em-dashes and en-dashes in every file in
    # that repo, UI copy and code comments alike. This is a build step writing
    # into it, so the rule is enforced here rather than remembered.
    offenders = dash_offenders(dest)
    if offenders:
        sys.exit("REFUSING: em/en dashes are banned on the target site "
                 f"(its CLAUDE.md). Fix in web/ and re-run: {offenders}")

    n = sum(1 for p in dest.rglob("*") if p.is_file())
    print(f"synced {n} files -> {dest}")
    leaked = [p for p in dest.rglob("firebase*.json")]
    if leaked:                       # belt and braces; the ignore above handles it
        sys.exit(f"REFUSING: firebase config reached the site: {leaked}")


if __name__ == "__main__":
    main(sys.argv)
