"""
Write the review sheet for the supports: every quotation and written use, readable on
a phone, so they can be checked before a child sees them (docs/05 decision 2).

    python3 tools/support_sheet.py

Writes experiments/2026-10-support-types-content.md. tests/test_supports.py fails if
the sheet and engine/supports.py disagree, so it cannot go stale.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "engine"))
OUT = ROOT / "experiments" / "2026-10-support-types-content.md"


def sheet():
    import supports
    lines = [
        "# The story support: what she will read after a miss",
        "",
        "Generated by `tools/support_sheet.py` from `engine/supports.py`. Do not edit here.",
        "",
        f"Reviewed: **{'yes' if supports.REVIEWED else 'not yet'}**. The experiment starts "
        "only once these have been read (`experiments/2026-10-support-types.md`).",
        "",
        f"{len(supports.QUOTES)} quotations, each checked word for word against its "
        "Project Gutenberg text by `python3 tools/find_quotes.py verify`, and "
        f"{len(supports.WRITTEN)} uses written where no quotation would do.",
        "",
        "## Quotations",
        "",
        "| Word | Sentence | From |",
        "|---|---|---|",
    ]
    for word in sorted(supports.QUOTES):
        ebook, text = supports.QUOTES[word]
        author, title, year = supports.BOOKS[ebook]
        lines.append(f"| {word} | {text.replace('|', '/')} | {author}, *{title}*, {year} |")
    lines += ["", "## Written for her", "", "| Word | Sentence |", "|---|---|"]
    for word in sorted(supports.WRITTEN):
        lines.append(f"| {word} | {supports.WRITTEN[word]} |")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    OUT.write_text(sheet())
    print(f"wrote {OUT.relative_to(ROOT)}")
